# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: cd server/ && deno fmt --check

      - name: Run linter
        run: deno lint
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.15.0
          cache: npm
          cache-dependency-path: client/package-lock.json
    
      - name: Install client dependencies
        run: cd client/ && npm install
      
      - name: Build client
        run: cd client/ && npm run build
      
      #  name: Run tests
      #  run: deno test -A --unstable
      
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: azar
          entrypoint: server/server.ts
